export const users: any = [
  {
    id: 1,
    type: 1,
    role: "Manager",
    phone: "01951700869",
    name: "Admin",
    password: "123456",
    email: "pronab.swe@gmail.com",
    location: "Mirpur-10",
    from: "01-01-2022",
    to: "01-01-2023",
  },
  {
    id: 2,
    type: 5,
    role: "Manager",
    name: "Nayeem",
    phone: "01994688976",
    password: "123456",
    email: "manager1@admin.com",
    location: "Mirpur-10",
    from: "01-01-2022",
    to: "01-01-2023",
  },
  {
    id: 3,
    type: 5,
    role: "Manager",
    phone: "01994688976",
    name: "Tonmoy",
    password: "123456",
    email: "manager2@admin.com",
    location: "Mirpur-10",
    from: "01-01-2022",
    to: "01-01-2023",
  },
  {
    id: 4,
    type: 5,
    role: "Manager",
    phone: "01994688976",
    name: "Biswas",
    password: "123456",
    email: "manager@admin.com",
    location: "Mirpur-10",
    from: "01-01-2022",
    to: "01-01-2023",
  },
];
export const roleList = [
  {
    id: 1,
    role: "SA",
    name: "Super Admin",
    type: 1,
  },
  {
    id: 2,
    role: "ORU",
    name: "Officer Reported Upon",
    type: 2,
  },
  {
    id: 3,
    role: "RIO",
    name: "Report Initialaling Officer",
    type: 3,
  },
  {
    id: 4,
    role: "CSO",
    name: "Counter Signing Officer",
    type: 4,
  },
  ,
  {
    id: 5,
    role: "MA",
    name: "Manager",
    type: 5,
  },
];

export const employeeList = [
  {
    id: 1,
    employee_name: "Tiger Nixon",
    employee_salary: 320800,
    employee_age: 61,
    profile_image: "",
    isActive: true,
  },
  {
    id: 2,
    employee_name: "Garrett Winters",
    employee_salary: 170750,
    employee_age: 63,
    profile_image: "",
    isActive: false,
  },
  {
    id: 3,
    employee_name: "Ashton Cox",
    employee_salary: 86000,
    employee_age: 66,
    profile_image: "",
    isActive: true,
  },
  {
    id: 4,
    employee_name: "Cedric Kelly",
    employee_salary: 433060,
    employee_age: 22,
    profile_image: "",
    isActive: true,
  },
  {
    id: 5,
    employee_name: "Airi Satou",
    employee_salary: 162700,
    employee_age: 33,
    profile_image: "",
    isActive: true,
  },
  {
    id: 6,
    employee_name: "Brielle Williamson",
    employee_salary: 372000,
    employee_age: 61,
    profile_image: "",
    isActive: true,
  },
  {
    id: 7,
    employee_name: "Herrod Chandler",
    employee_salary: 137500,
    employee_age: 59,
    profile_image: "",
    isActive: true,
  },
  {
    id: 8,
    employee_name: "Rhona Davidson",
    employee_salary: 327900,
    employee_age: 55,
    profile_image: "",
    isActive: true,
  },
  {
    id: 9,
    employee_name: "Colleen Hurst",
    employee_salary: 205500,
    employee_age: 39,
    profile_image: "",
    isActive: true,
  },
  {
    id: 10,
    employee_name: "Sonya Frost",
    employee_salary: 103600,
    employee_age: 23,
    profile_image: "",
    isActive: true,
  },
  {
    id: 11,
    employee_name: "Jena Gaines",
    employee_salary: 90560,
    employee_age: 30,
    profile_image: "",
    isActive: true,
  },
  {
    id: 12,
    employee_name: "Quinn Flynn",
    employee_salary: 342000,
    employee_age: 22,
    profile_image: "",
    isActive: true,
  },
  {
    id: 13,
    employee_name: "Charde Marshall",
    employee_salary: 470600,
    employee_age: 36,
    profile_image: "",
    isActive: true,
  },
  {
    id: 14,
    employee_name: "Haley Kennedy",
    employee_salary: 313500,
    employee_age: 43,
    profile_image: "",
    isActive: true,
  },
  {
    id: 15,
    employee_name: "Tatyana Fitzpatrick",
    employee_salary: 385750,
    employee_age: 19,
    profile_image: "",
    isActive: true,
  },
  {
    id: 16,
    employee_name: "Michael Silva",
    employee_salary: 198500,
    employee_age: 66,
    profile_image: "",
    isActive: true,
  },
  {
    id: 17,
    employee_name: "Paul Byrd",
    employee_salary: 725000,
    employee_age: 64,
    profile_image: "",
    isActive: true,
  },
  {
    id: 18,
    employee_name: "Gloria Little",
    employee_salary: 237500,
    employee_age: 59,
    profile_image: "",
    isActive: true,
  },
  {
    id: 19,
    employee_name: "Bradley Greer",
    employee_salary: 132000,
    employee_age: 41,
    profile_image: "",
    isActive: true,
  },
  {
    id: 20,
    employee_name: "Dai Rios",
    employee_salary: 217500,
    employee_age: 35,
    profile_image: "",
    isActive: true,
  },
  {
    id: 21,
    employee_name: "Jenette Caldwell",
    employee_salary: 345000,
    employee_age: 30,
    profile_image: "",
    isActive: true,
  },
  {
    id: 22,
    employee_name: "Yuri Berry",
    employee_salary: 675000,
    employee_age: 40,
    profile_image: "",
    isActive: true,
  },
  {
    id: 23,
    employee_name: "Caesar Vance",
    employee_salary: 106450,
    employee_age: 21,
    profile_image: "",
    isActive: true,
  },
  {
    id: 24,
    employee_name: "Doris Wilder",
    employee_salary: 85600,
    employee_age: 23,
    profile_image: "",
    isActive: true,
  },
];

export const sortList = [
  {
    id: 1,
    name: "Low to High",
    value: 1,
  },
  {
    name: "High to Low",
    id: 2,
    value: 2,
  },
];
